baseURL = "https://xuemark.github.io/"
ignoreFiles = [ "\\.files/README.md$",  ]
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Mark Page"
theme = "hugo-theme-learn"
uglyurls = false
sectionPagesMenu = "main"
relativeURLs = true

[blackfriday]
  hrefTargetBlank = true

[params]
  editURL = "https://github.com/xuemark/xuemark.github.io/origin/"
  themeVariant = "mine"
  showVisitedLinks = false
  author = "Mark Xue"
  description = "Solution Architect"
  disableSearch = true
  disableAssetsBusting = false
  disableShortcutsTitle = true
  branch = "master"
  pygmentsUseClasses = true
  pygmentsCodeFences = true
  pygmentsCodefencesGuessSyntax = true
  pygmentsStyle = "tango"
  codeRepoName = "xuemark/xuemark.github.io"


[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub Project"
url = "https://github.com/xuemark/xuemark.github.io"
weight = 30

[[menu.shortcuts]]
name = "<i class='fas fa-envelope'></i> Have questions?"
url = "https://github.com/xuemark/xuemark.github.io/issues"
weight = 40

[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]